baseURL: https://blog.twomatwo.me
languageCode: en-us
title: blog.twomatwo.me
theme: PaperMod 

enableEmoji: true 

params:
  defaultTheme: auto # dark, light, auto

  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  math: true
  
  homeInfoParams:
    Title: "Hello Stranger!"
    Content: Welcome to my blog. Or you can visit my main site [here](https://twomatwo.me)
  socialIcons: 
    - name: github
      url: "https://github.com/twomatwo"
    - name: bilibili
      url: "https://bilibili.com"
    - name: email
      url: "mailto:non-existed AT outlook.com"
      
  cover:
    linkFullImages: true

menu:
  main:
    - identifier: index
      name: Index
      url: /posts/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Timeline
      url: /archives/
      weight: 30


markup:
  goldmark:
    renderer:
      unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
  highlight:
    # anchorLineNos: true
    codeFences: true  
    guessSyntax: true
    lineNos: true
    # noClasses: false
    # style: monokai
    style: darcula

  # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
  # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
  # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
  # lineNoStart：行号从编号几开始，一般从 1 开始。
  # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
  # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
  # noClasses：使用 class 标签，而不是内嵌的内联样式
